[package]
name = "utk"
version = "0.1.0"
authors = ["link"]
edition = "2018"

[dependencies]
async-std = "*"
actix-web = "*"
tokio = "*"
hyper = "*"
image = "*"
winit = "*"
num-complex = "*"
winit-blit = {git="https://github.com/rust-windowing/winit-blit"}